#include "PlayerSenseComponent.h"
#include "GameFramework/Actor.h"

UPlayerSenseComponent::UPlayerSenseComponent(){PrimaryComponentTick.bCanEverTick=true;}
void UPlayerSenseComponent::RegisterBoundaryTarget(AActor* A,bool Available){if(!IsValid(A))return;for(auto& T:Targets)if(T.Actor==A){T.bAvailable=Available;return;}FRegisteredSenseTarget T;T.Actor=A;T.bAvailable=Available;Targets.Add(T);}
void UPlayerSenseComponent::SetBoundaryTargetAvailable(AActor* A,bool Available){for(auto& T:Targets)if(T.Actor==A){T.bAvailable=Available;return;}}
void UPlayerSenseComponent::ClearBoundaryTargets(){Targets.Empty();Reading=FBoundarySenseReading();}
void UPlayerSenseComponent::BeginBoundarySense(){if(bBoundaryActive)return;bBoundaryActive=true;bSenseUsedSincePurify=true;BoundaryDuration=0;bStrongLogged=false;UE_LOG(LogTemp,Display,TEXT("PLAYER_SENSE sword_start"));}
void UPlayerSenseComponent::EndBoundarySense(){if(!bBoundaryActive)return;bBoundaryActive=false;Reading=FBoundarySenseReading();UE_LOG(LogTemp,Display,TEXT("PLAYER_SENSE sword_end duration=%.2f"),BoundaryDuration);}
void UPlayerSenseComponent::BeginCorruptionSense(){if(bCorruptionActive)return;bCorruptionActive=true;bSenseUsedSincePurify=true;CorruptionDuration=0;bDangerLogged=false;UE_LOG(LogTemp,Display,TEXT("PLAYER_SENSE arm_start"));}
void UPlayerSenseComponent::EndCorruptionSense(){if(!bCorruptionActive)return;bCorruptionActive=false;RiskRemaining=RiskTailSeconds;UE_LOG(LogTemp,Display,TEXT("PLAYER_SENSE arm_end duration=%.2f risk_tail=%.2f"),CorruptionDuration,RiskRemaining);}
void UPlayerSenseComponent::ResetSense(){if(bBoundaryActive)EndBoundarySense();if(bCorruptionActive)EndCorruptionSense();bBoundaryActive=bCorruptionActive=bSenseUsedSincePurify=false;BoundaryDuration=CorruptionDuration=RiskRemaining=0;Warning=ECorruptionWarning::None;Reading=FBoundarySenseReading();UE_LOG(LogTemp,Display,TEXT("PLAYER_SENSE reset"));}
void UPlayerSenseComponent::NotifyPurifyAfterSense(){if(bSenseUsedSincePurify)UE_LOG(LogTemp,Display,TEXT("PLAYER_SENSE purify_after_sense"));bSenseUsedSincePurify=false;}
void UPlayerSenseComponent::TickComponent(float Dt,ELevelTick T,FActorComponentTickFunction* F){Super::TickComponent(Dt,T,F);if(!FMath::IsFinite(Dt)||Dt<=0)return;if(!bCorruptionActive)RiskRemaining=FMath::Max(0.f,RiskRemaining-Dt);else{CorruptionDuration+=Dt;if(Warning==ECorruptionWarning::Danger&&!bDangerLogged){bDangerLogged=true;UE_LOG(LogTemp,Display,TEXT("PLAYER_SENSE danger_detected"));}}if(!bBoundaryActive)return;BoundaryDuration+=Dt;Reading=FBoundarySenseReading();const AActor* O=GetOwner();if(!O)return;float Best=-1;for(const auto& Item:Targets){AActor* A=Item.Actor.Get();if(!Item.bAvailable||!IsValid(A))continue;const FVector Delta=A->GetActorLocation()-O->GetActorLocation();const float D=Delta.Size();const FVector Dir=Delta.GetSafeNormal();const float Alignment=FMath::Clamp((FVector::DotProduct(O->GetActorForwardVector(),Dir)+1.f)*.5f,0.f,1.f);const float S=Alignment*FMath::Clamp(1.f-D/FMath::Max(1.f,MaximumDistance),0.f,1.f);if(S>Best){Best=S;Reading.Direction=Dir;Reading.Strength=S;Reading.Target=A;Reading.Distance=D<=NearDistance?ESenseDistanceBand::Near:D<=MediumDistance?ESenseDistanceBand::Medium:ESenseDistanceBand::Far;}}if(Reading.Strength>=.67f&&!bStrongLogged){bStrongLogged=true;UE_LOG(LogTemp,Display,TEXT("PLAYER_SENSE strong_detection strength=%.2f"),Reading.Strength);}}
FString UPlayerSenseComponent::GetBoundaryStrengthLabel()const{return Reading.Strength>=.67f?TEXT("STRONG"):Reading.Strength>=.34f?TEXT("MEDIUM"):TEXT("WEAK");}
FString UPlayerSenseComponent::GetCorruptionWarningLabel()const{switch(GetCorruptionWarning()){case ECorruptionWarning::Danger:return TEXT("DANGER");case ECorruptionWarning::Safe:return TEXT("SAFE");case ECorruptionWarning::Transition:return TEXT("TRANSITION");default:return TEXT("QUIET");}}
